name: Deploy to Maven Central

on:
  push:
    tags:
      - 'v*'  # ينفذ فقط عند عمل tag زي v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ضروري علشان يرفع لـ GitHub Releases

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean package -DskipTests=true

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import

      - name: Sign Artifacts
        run: |
          for file in target/*.jar target/*.pom; do
            gpg --batch --yes --armor --pinentry-mode loopback \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --output "$file.asc" --detach-sign "$file"
          done

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
            target/*.jar.asc
            target/*.pom
            target/*.pom.asc
