name: Deploy to Central via GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests=true

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import

      - name: Sign Artifacts
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          for ext in jar jar.asc pom pom.asc sources.jar sources.jar.asc javadoc.jar javadoc.jar.asc; do
            touch target/appium-scroll-utils-$VERSION.$ext
          done
          for file in target/appium-scroll-utils-$VERSION.jar target/appium-scroll-utils-$VERSION-sources.jar target/appium-scroll-utils-$VERSION-javadoc.jar target/appium-scroll-utils-$VERSION.pom; do
            gpg --batch --yes --armor --pinentry-mode loopback \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --output "$file.asc" --detach-sign "$file"
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/appium-scroll-utils-*.jar
            target/appium-scroll-utils-*.jar.asc
            target/appium-scroll-utils-*.pom
            target/appium-scroll-utils-*.pom.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
