name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Extract version and target path
        id: vars
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          TARGET_PATH=target/io/github/ahmedraafat2/appium-scroll-utils/$VERSION
          echo "target_path=$TARGET_PATH" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B clean install -Pcentral-release

      - name: Create target path and move files
        run: |
          mkdir -p ${{ steps.vars.outputs.target_path }}
          cp target/appium-scroll-utils-${{ steps.vars.outputs.VERSION }}* \
            ${{ steps.vars.outputs.target_path }}

      - name: Sign artifacts with GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          cd "${{ steps.vars.outputs.target_path }}"
          for file in *.jar *.pom; do
            gpg --batch --yes --passphrase "$GPG_PASSPHRASE" \
              -a -b "$file"
          done

      - name: Generate checksum files
        run: |
          cd "${{ steps.vars.outputs.target_path }}"
          for file in *.jar *.pom; do
            md5sum "$file" > "$file.md5"
            sha1sum "$file" > "$file.sha1"
          done

      - name: Create zip bundle
        run: |
          cd "${{ steps.vars.outputs.target_path }}"
          zip -r ../../../central-bundle.zip .

      - name: Upload bundle to Maven Central
        run: |
          curl -u "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_TOKEN }}" \
            -X POST "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC" \
            -F "bundle=@../../../central-bundle.zip"
