name: Release to GitHub & Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and package
        run: mvn clean package source:jar javadoc:jar -DskipTests

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          gpg --list-keys

      - name: Generate and Sign Artifacts
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn help:effective-pom -Doutput=target/appium-scroll-utils-$VERSION.pom
          for file in target/appium-scroll-utils-$VERSION*.{jar,pom}; do
            gpg --batch --yes --armor --pinentry-mode loopback \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --output "$file.asc" --detach-sign "$file"
          done

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/appium-scroll-utils-1.0.33.jar
            target/appium-scroll-utils-1.0.33-sources.jar
            target/appium-scroll-utils-1.0.33-javadoc.jar
            target/appium-scroll-utils-1.0.33.pom
            target/appium-scroll-utils-1.0.33.jar.asc
            target/appium-scroll-utils-1.0.33-sources.jar.asc
            target/appium-scroll-utils-1.0.33-javadoc.jar.asc
            target/appium-scroll-utils-1.0.33.pom.asc
          
