name: Release to GitHub & Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          gpg --list-keys


      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/appium-scroll-utils-*.jar
            target/appium-scroll-utils-*-sources.jar
            target/appium-scroll-utils-*-javadoc.jar
            target/appium-scroll-utils-*.pom
            target/appium-scroll-utils-*.asc
            

      - name: Build and deploy to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # إعداد إعدادات Maven
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>\${OSSRH_USERNAME}</username>
                <password>\${OSSRH_PASSWORD}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>gpg</id>
                <properties>
                  <gpg.passphrase>\${GPG_PASSPHRASE}</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
          </settings>
          EOF

          # تنفيذ عملية النشر
          mvn clean deploy -DskipTests -P gpg