name: Release to GitHub & Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and package
        run: mvn clean package source:jar javadoc:jar -DskipTests

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          gpg --list-keys

      - name: Generate and Sign Artifacts
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cp pom.xml target/appium-scroll-utils-$VERSION.pom
          for file in target/appium-scroll-utils-$VERSION*.{jar,pom}; do
            gpg --batch --yes --armor --pinentry-mode loopback \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --output "$file.asc" --detach-sign "$file"
          done

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/appium-scroll-utils-*.jar
            target/appium-scroll-utils-*.pom
            target/appium-scroll-utils-*.jar.asc
            target/appium-scroll-utils-*.pom.asc

      - name: Create central-bundle.zip
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          ARTIFACT_ID="appium-scroll-utils"
          mkdir -p "$ARTIFACT_ID/$VERSION"
          cp "target/$ARTIFACT_ID-$VERSION.jar" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.jar.asc" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.pom" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.pom.asc" "$ARTIFACT_ID/$VERSION/"
          zip -r central-bundle.zip "$ARTIFACT_ID"
      

      - name: Deploy bundle via API
        run: |
          curl -u "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_TOKEN }}" \
            -X POST "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC" \
            -F "bundle=@central-bundle.zip"
