name: Release to Maven Central

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Maven Central via Central Portal
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for uploading assets to the release

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build & Package
        run: mvn -B clean package source:jar javadoc:jar -DskipTests

      - name: Sign Artifacts
        uses: s4u/pgp-sign-action@v1.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          artifacts: |
            target/*.jar
            target/*.pom

      - name: Upload signed artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
            target/*.pom
            target/*.asc
