name: Release to Maven Central via GitHub Releases

on:
  release:
    types: [published]  # يعمل عند عمل release يدوي أو عن طريق tag

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Sign
        run: mvn clean install -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"

      - name: Upload signed artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
            target/*.jar.asc
            target/*.pom
            target/*.pom.asc
