name: Publish to Maven Central (via Central Portal)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Import GPG key
        run: |
          echo "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
        env:
          GPG_TTY: $(tty)

      - name: Set GPG Key ID
        id: gpg
        run: |
          echo "key_id=$(gpg --list-keys --with-colons | grep pub | cut -d ':' -f5)" >> $GITHUB_OUTPUT

      - name: Build and sign artifacts
        run: |
          mvn clean install -Psign-artifacts \
            -Dgpg.keyname=${{ steps.gpg.outputs.key_id }} \
            -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
            -Dgpg.executable=gpg \
            -Dgpg.secretKeyring=~/.gnupg/secring.gpg

      - name: Prepare central-bundle.zip
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          ARTIFACT_ID="appium-scroll-utils"
          mkdir -p "$ARTIFACT_ID/$VERSION"
          cp "target/$ARTIFACT_ID-$VERSION.jar" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.jar.asc" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION-sources.jar" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION-sources.jar.asc" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION-javadoc.jar" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION-javadoc.jar.asc" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.pom" "$ARTIFACT_ID/$VERSION/"
          cp "target/$ARTIFACT_ID-$VERSION.pom.asc" "$ARTIFACT_ID/$VERSION/"
          zip -r central-bundle.zip "$ARTIFACT_ID"


      - name: Upload bundle to Central Portal
        run: |
          curl -u "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_TOKEN }}" \
            -X POST "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC" \
            -F "bundle=@central-bundle.zip"
