name: Release to GitHub & Maven Central

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build and package
        run: mvn -B clean deploy -DskipTests -Prelease

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign Artifacts
        run: mvn -B verify -Psign-artifacts -DskipTests

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
            target/*.pom
            target/*.asc

      - name: Publish to Maven Central via Central Portal
        uses: sonatype-central/publish-release@v1
        with:
          coordinates: 'io.github.ahmedraafat2:appium-scroll-utils'
          github-token: ${{ secrets.GITHUB_TOKEN }}
